version: '3.8'

services:
  auth_db:
    image: mariadb:latest
    container_name: oauth_db
    environment:
      - MARIADB_USER=superAdmin
      - MARIADB_ROOT_PASSWORD=estacionamiento2023
      - MARIADB_DATABASE=auth_db
    ports:
      - "3306:3306"